# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
version: '3'

env:
  ENTRY_POINT: main
  SOURCE_FOLDER: example
  BUILD_FOLDER: build
  COVERAGE_OUT_FILE: coverage.out
  COVERAGE_HTML_FILE: coverage.html
  SWAGGER_INPUT_FOLDER: ./example
  SWAGGER_OUTPUT_FOLDER: docs
  GO_VERSION: 1.21.6
  TASK_VERSION: v3.34.1
  GITLAB_TOKEN: ${GITLAB_TOKEN}
  KUSTOMIZE_FOLDER_INPUT: kustomize

tasks:
  k:build:
    desc: build k8s build
    deps: [ create-folder ]
    cmds:
      - kustomize build $KUSTOMIZE_FOLDER_INPUT/overlays/local --output $BUILD_FOLDER/build.yaml --load-restrictor LoadRestrictionsNone
  docker:build:
    desc: docker build
    cmds:
      - echo {{.GO_VERSION}} {{.GITLAB_TOKEN}}
      - docker build -t {{.CLI_ARGS}} . --build-arg GO_VERSION={{.GO_VERSION}} --build-arg GITLAB_TOKEN={{.GITLAB_TOKEN}} --build-arg TASK_VERSION={{.TASK_VERSION}}
  docker:deploy:
    desc: docker deploy
    cmds:
      - docker run -p 8080:8080 {{.CLI_ARGS}}
  lsif:
    desc: Code Intelligence
    cmds:
      - .gitlab/code_navigation.sh
  lint:
    desc: Use golangci-lint (.golangci.yml).
    cmds:
      - golangci-lint run --fix
  test:race:
    desc: Run race test.
    cmds:
      - go test -race ./...
  test:
    desc: Run test.
    cmds:
      - go test ./...
  download:
    desc: Run go mod tidy.
    cmds:
      - go mod tidy
  upgrade:
    desc: Check for latest direct dependencies.
    cmds:
      - go-mod-upgrade
  update:
    desc: Check for latest direct dependencies
    deps: [ download ]
    cmds:
      - go list -mod=mod -u -m -json all | go-mod-outdated -update -direct
  swagger:
    desc: Generate RESTful API documentation with Swagger.
    cmds:
      - swag init -d $SWAGGER_INPUT_FOLDER -g $ENTRY_POINT.go -d examples/full,core -o $SWAGGER_OUTPUT_FOLDER --parseGoList
  create-folder:
    cmds:
      - echo '{{OS}} {{ARCH}}'
      - echo '{{fromSlash .BUILD_FOLDER}}'
      - '{{if eq OS "darwin"}}[ -d "$BUILD_FOLDER" \] & rm -rf "$BUILD_FOLDER" && mkdir -p "$BUILD_FOLDER/.."{{end}}'
    internal: true
  build:
    desc: Build the go EXECUTABLE.
    deps: [ create-folder ]
    generates:
      - server
    cmds:
      - go build -v $SOURCE_FOLDER/$ENTRY_POINT.go
      - mv $ENTRY_POINT $BUILD_FOLDER
  run:
    desc: main()
    cmds:
      - go run $SOURCE_FOLDER/$ENTRY_POINT.go
  uml:
    desc: Generate UML documentation with PlantUML.
    cmds:
      - go get github.com/jfeliu007/goplantuml/parser
      - go install github.com/jfeliu007/goplantuml/cmd/goplantuml@latest
      - |
        goplantuml -title {{.APP_NAME}} \
          -show-compositions -show-aggregations -aggregate-private-members \
          -recursive ./ > docs/structures.puml
      - go mod tidy
  all:
    desc: Run relevant tasks.
    cmds:
      - task: download
      - task: lint
      - task: test
      - task: swagger
  default:
    desc: Run [build] task.
    cmds:
      - task: all
