{
 "title": "APM",
 "description": "Dashboard for Go Fiber",
 "tags": [
  "apm",
  "golang",
  "fiber",
  "observability"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(http_requests_total, namespace)"
    }
   },
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(http_requests_total, application)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(http_requests_total{application=~\"$application\"}, instance)"
    }
   },
   {
    "name": "path",
    "label": "Path",
    "query": {
     "query": "label_values(http_requests_total{application=~\"$application\", instance=~\"$instance\"}, path)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "histogram_quantile(0.5, sum by (application, le) (rate(http_request_duration_seconds_bucket{application=~\"$application\",instance=~\"$instance\", namespace=~\"$namespace\"}[5m])))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ application }} - p50",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "expr": "histogram_quantile(0.95, sum by (application, le) (rate(http_request_duration_seconds_bucket{application=~\"$application\",instance=~\"$instance\", path=~\"$handler\", namespace=~\"$namespace\"}[5m])))",
     "legendFormat": "{{ application }} - p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (application, le) (rate(http_request_duration_seconds_bucket{application=~\"$application\",instance=~\"$instance\", path=~\"$handler\", namespace=~\"$namespace\"}[5m])))",
     "legendFormat": "{{ application }} - p99"
    }
   ]
  },
  {
   "title": "Errors - % (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(rate(http_requests_total{application=~\"$application\",instance=~\"$instance\", path=~\"$path\", namespace=~\"$namespace\", status_code=~\"500|503\"}[5m])) by (application)/sum(rate(http_requests_total{application=~\"$application\",instance=~\"$instance\", path=~\"$path\", namespace=~\"$namespace\"}[5m])) by (application)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ application }} - {{ method }} {{handler}}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "RPM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(rate(http_requests_total{application=~\"$application\",instance=~\"$instance\", path=~\"$path\", namespace=~\"$namespace\"}[2m])) by (application) * 60",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ application }}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Response time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "histogram_quantile(0.5, sum by (application, le) (rate(http_request_duration_seconds_bucket{application=~\"$application\",instance=~\"$instance\", path=~\"$path\", namespace=~\"$namespace\"}[5m])))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ application }} - p50",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "expr": "histogram_quantile(0.95, sum by (application, le) (rate(http_request_duration_seconds_bucket{application=~\"$application\",instance=~\"$instance\", path=~\"$handler\", namespace=~\"$namespace\"}[5m])))",
     "legendFormat": "{{ application }} - p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (application, le) (rate(http_request_duration_seconds_bucket{application=~\"$application\",instance=~\"$instance\", path=~\"$handler\", namespace=~\"$namespace\"}[5m])))",
     "legendFormat": "{{ application }} - p99"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 8 },
   "targets": [
    {
     "expr": "up{name=~\"$application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic by instance - Req/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(rate(http_requests_total{application=~\"$application\",instance=~\"$instance\", path=~\"$path\", namespace=~\"$namespace\"}[2m])) by (application, instance)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ application }} - {{ instance }}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Latency by path",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "histogram_quantile(0.5, sum by (application, method, path, le) (rate(http_request_duration_seconds_bucket{application=~\"$application\",instance=~\"$instance\", path=~\"$path\", namespace=~\"$namespace\"}[5m])))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ application }} - {{ method }} {{ path }} - p50",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "expr": "histogram_quantile(0.95, sum by (application, method, path, le) (rate(http_request_duration_seconds_bucket{application=~\"$application\",instance=~\"$instance\", path=~\"$path\", namespace=~\"$namespace\"}[5m])))",
     "legendFormat": "{{ application }} - {{ method }} {{ path }} - p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (application, method, path, le) (rate(http_request_duration_seconds_bucket{application=~\"$application\",instance=~\"$instance\", path=~\"$path\", namespace=~\"$namespace\"}[5m])))",
     "legendFormat": "{{ application }} - {{ method }} {{ path }} - p99"
    }
   ]
  },
  {
   "title": "Traffic - Req/s by path",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(rate(http_requests_total{application=~\"$application\",instance=~\"$instance\", path=~\"$path\", namespace=~\"$namespace\"}[2m])) by (application, method, path)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ application }} - {{ method }} {{path}}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Latency by instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "histogram_quantile(0.5, sum by (application, instance, le) (rate(http_request_duration_seconds_bucket{application=~\"$application\",instance=~\"$instance\", path=~\"$path\", namespace=~\"$namespace\"}[5m])))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ application }} - {{ instance }} - p50",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "expr": "histogram_quantile(0.95, sum by (application, instance, le) (rate(http_request_duration_seconds_bucket{application=~\"$application\",instance=~\"$instance\", path=~\"$path\", namespace=~\"$namespace\"}[5m])))",
     "legendFormat": "{{ application }} - {{ instance }} - p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (application, instance, le) (rate(http_request_duration_seconds_bucket{application=~\"$application\",instance=~\"$instance\", path=~\"$path\", namespace=~\"$namespace\"}[5m])))",
     "legendFormat": "{{ application }} - {{ instance }} - p99"
    }
   ]
  },
  {
   "title": "Errors - % by handler (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum by(application, method, path) (rate(http_requests_total{application=~\"$application\", instance=~\"$instance\", path=~\"$path\", namespace=~\"$namespace\", status_code=~\"50*\"}[5m])) / sum by(application, method, path) (rate(http_requests_total{application=~\"$application\", instance=~\"$instance\", path=~\"$path\", namespace=~\"$namespace\"}[5m]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ application }} - {{ method }} {{path}}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Errors - % (4xx)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(rate(http_requests_total{application=~\"$application\",instance=~\"$instance\", path=~\"$path\", namespace=~\"$namespace\", status_code=~\"401|404|429\"}[5m])) by (application)/sum(rate(http_requests_total{application=~\"$application\",instance=~\"$instance\", path=~\"$path\", namespace=~\"$namespace\"}[5m])) by (application)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ application }}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Latency 99p by instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (application, instance, le) (rate(http_request_duration_seconds_bucket{application=~\"$application\",instance=~\"$instance\", path=~\"$path\", namespace=~\"$namespace\"}[5m])))",
     "legendFormat": "{{ application }} - {{ instance }} - p99"
    }
   ]
  }
 ]
}