// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/message": {
            "get": {
                "description": "Get message",
                "produces": [
                    "application/json",
                    "application/problem+json"
                ],
                "tags": [
                    "Messages"
                ],
                "summary": "Get message",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errorx.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errorx.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "errorx.Error": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string",
                    "example": "Your current balance is 30, but that costs 50."
                },
                "instance": {
                    "type": "string",
                    "example": "/account/12345/msgs/abc"
                },
                "status": {
                    "type": "integer",
                    "example": 403
                },
                "title": {
                    "type": "string",
                    "example": "You do not have enough credit."
                },
                "type": {
                    "type": "string",
                    "example": "https://example.com/probs/out-of-credit"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "v1.",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Backend IskayPet SDK",
	Description:      "Provide an interface to build core APIs.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
